USE [GD1C2021]
GO


DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_ACCESORIO
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_CIUDAD
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_SUCURSAL
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_CLIENTE
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_DISCO_RIGIDO
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_CPU
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_GPU
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_RAM
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_PC
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_COMPRA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_FACTURA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_PC_X_COMPRA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_PC_X_FACTURA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_ACCESORIO_X_COMPRA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_ACCESORIO_X_FACTURA
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_FABRICANTE

DROP TABLE [BREAKFAST_CLUB].[ACCESORIO_X_FACTURA]
DROP TABLE [BREAKFAST_CLUB].[ACCESORIO_X_COMPRA]
DROP TABLE [BREAKFAST_CLUB].[PC_X_COMPRA]
DROP TABLE [BREAKFAST_CLUB].[PC_X_FACTURA]
DROP TABLE [BREAKFAST_CLUB].[FACTURA]
DROP TABLE [BREAKFAST_CLUB].[COMPRA]
DROP TABLE [BREAKFAST_CLUB].[ACCESORIO]
DROP TABLE [BREAKFAST_CLUB].[SUCURSAL]
DROP TABLE [BREAKFAST_CLUB].[CLIENTE]
DROP TABLE [BREAKFAST_CLUB].[CIUDAD]
DROP TABLE [BREAKFAST_CLUB].[PC]
DROP TABLE [BREAKFAST_CLUB].[GPU]
DROP TABLE [BREAKFAST_CLUB].[CPU]
DROP TABLE [BREAKFAST_CLUB].[DISCO_RIGIDO]
DROP TABLE [BREAKFAST_CLUB].[RAM]
DROP TABLE [BREAKFAST_CLUB].[FABRICANTE]

DROP SCHEMA [BREAKFAST_CLUB]