USE [GD1C2021]
GO



DROP FUNCTION [BREAKFAST_CLUB].obtener_cod_mes_anterior
DROP FUNCTION [BREAKFAST_CLUB].obtener_stock_disponible_accesorio
DROP FUNCTION [BREAKFAST_CLUB].obtener_stock_disponible_pc
DROP FUNCTION [BREAKFAST_CLUB].obtener_rango_edad
DROP FUNCTION [BREAKFAST_CLUB].obtener_codigo_tiempo

DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_CLIENTE
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_TIEMPO
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_HECHOS_PC
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_HECHOS_ACCESORIOS
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_SUCURSAL
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_PC
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_GPU
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_CPU
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_DISCO_RIGIDO
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_RAM
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_ACCESORIO
DROP PROCEDURE [BREAKFAST_CLUB].PRC_INSERT_BI_FABRICANTE
DROP PROCEDURE [BREAKFAST_CLUB].PRC_BI_SET_STOCK_PC
DROP PROCEDURE [BREAKFAST_CLUB].PRC_BI_SET_STOCK_ACCESORIOS

DROP TABLE [BREAKFAST_CLUB].[BI_HECHOS_PC]
DROP TABLE [BREAKFAST_CLUB].[BI_HECHOS_ACCESORIOS]
DROP TABLE [BREAKFAST_CLUB].[BI_TIEMPO]
DROP TABLE [BREAKFAST_CLUB].[BI_CLIENTE]
DROP TABLE [BREAKFAST_CLUB].[BI_SUCURSAL]
DROP TABLE [BREAKFAST_CLUB].[BI_PC]
DROP TABLE [BREAKFAST_CLUB].[BI_GPU]
DROP TABLE [BREAKFAST_CLUB].[BI_CPU]
DROP TABLE [BREAKFAST_CLUB].[BI_DISCO_RIGIDO]
DROP TABLE [BREAKFAST_CLUB].[BI_RAM]
DROP TABLE [BREAKFAST_CLUB].[BI_ACCESORIO]
DROP TABLE [BREAKFAST_CLUB].[BI_FABRICANTE]

